### ISSUE TITLE
Is this project working?

### ISSUE THREAD

**Issue by jitendra3109** [johnyf/openstreetmap#2]
Hi! I think it has been 4 years and Actually I do not know is it working.
I was looking how to get area wise vehicle profile in OSM.
If you could help then please :100:

**Comment by johnyf** [comment]
The code works, except perhaps for small changes in how OpenStreetmap represents map information.

**Comment by jitendra3109** [comment]
> how OpenStreetMap represents map information.
Did not get it.
I was using [graphhopper](https://www.graphhopper.com/) {[code](https://github.com/graphhopper/graphhopper)}and [jsrpit](https://github.com/graphhopper/jsprit) open source lib but problem is that I good accuracy of ETAs

**Comment by johnyf** [comment]
If recently there have been any minor modifications in details of the XML format that OpenStreetmap uses, then those have not been reflected in this package yet.

**Comment by jitendra3109** [comment]
Thaks you. Looking at issue I raised. Will get help. See you in some time.
